(equal_c *TOP* Thing)
(equal_c *TOP* NamedIndividual)
(implies_c Person Na8c1ce2781c946548d749105b7b7f383)
(implies_c Marriage DomainEntity)
(implies_c Male Sex)
(implies_c Person DomainEntity)
(implies_c Female Sex)
(implies_c Sex DomainEntity)
(disjoint_c Person Sex)
(disjoint_c Female Male)
(equal_c Sex Nb4435dd42ee24e968ecaf107cf0bd9a2)
(equal_c Woman Nd57a800a6101406fac6adc082c45f664)
(equal_c Person N9ed67fae8fbd453d9ab1afc333ad90c2)
(equal_c Ancestor N47ee2d091b4140c8a1dc111643ca67d4)
(equal_c Man N65005ffcdb474c44ab8eeb170486b276)
(disjoint_c Female Male)
(equal_c Nb4435dd42ee24e968ecaf107cf0bd9a2 (or Female Male))
(disjoint_c Man Woman)
(equal_c N9ed67fae8fbd453d9ab1afc333ad90c2 (or Man Woman))
(equal_c Nd57a800a6101406fac6adc082c45f664 (and Person N7bc3c134e2fa42f48f58eac9a3e9cb13))
(equal_c N47ee2d091b4140c8a1dc111643ca67d4 (and Person N6738d7f305d14829bc5b7b94907269f4))
(equal_c N65005ffcdb474c44ab8eeb170486b276 (and Person N11be49582c4f4ed6ac07cb0ff61976a4))
(different i16 i11 i10 i35 i12 i40 i28 i29 i20 i21 i22 i23 i24 i25 i26 i27 i9 i8 i1 i0 i3 i2 i5 i4 i7 i6 i39 i38 i19 i18 i33 i32 i17 i30 i37 i36 i13 i34 i15 i14 i31 i42 i41 i53 i52 i45 i50 i43 i48 i55 i47 i46 i51 i54 i49 i44)
(different i16 i11 i10 i35 i12 i40 i28 i29 i20 i21 i22 i23 i24 i25 i26 i27 i9 i8 i1 i0 i3 i2 i5 i4 i7 i6 i39 i38 i19 i18 i33 i32 i17 i30 i37 i36 i13 i34 i15 i14 i31 i42 i41 i53 i52 i45 i50 i43 i48 i55 i47 i46 i51 i54 i49 i44)
(equal_c Na8c1ce2781c946548d749105b7b7f383 (some hasSex Sex))
(equal_c N6738d7f305d14829bc5b7b94907269f4 (some isAncestorOf Person))
(equal_c N11be49582c4f4ed6ac07cb0ff61976a4 (some hasSex Male))
(equal_c N7bc3c134e2fa42f48f58eac9a3e9cb13 (some hasSex Female))
(instance i13 Thing)
(instance i9 Thing)
(instance i34 Thing)
(instance i36 Thing)
(instance i1 Thing)
(instance i32 Thing)
(instance i42 Thing)
(instance i55 Thing)
(instance i4 Thing)
(instance i15 Thing)
(instance i41 Thing)
(instance i52 Thing)
(instance i45 Thing)
(instance i40 Thing)
(instance i35 Thing)
(instance i14 Thing)
(instance i2 Thing)
(instance i18 Thing)
(instance i30 Thing)
(instance i0 Thing)
(instance i38 Thing)
(instance i20 Thing)
(instance i51 Thing)
(instance i23 Thing)
(instance i33 Thing)
(instance i8 Thing)
(instance i46 Thing)
(instance i10 Thing)
(instance i19 Thing)
(instance i3 Thing)
(instance i53 Thing)
(instance i6 Thing)
(instance i49 Thing)
(instance i12 Thing)
(instance i22 Thing)
(instance i50 Thing)
(instance i48 Thing)
(instance i7 Thing)
(instance i17 Thing)
(instance i25 Thing)
(instance i43 Thing)
(instance i44 Thing)
(instance i54 Thing)
(instance i29 Thing)
(instance i27 Thing)
(instance i37 Thing)
(instance i26 Thing)
(instance i16 Thing)
(instance i24 Thing)
(instance i31 Thing)
(instance i11 Thing)
(instance i28 Thing)
(instance i39 Thing)
(instance i47 Thing)
(instance i5 Thing)
(instance i21 Thing)
(instance i30 NamedIndividual)
(instance i0 NamedIndividual)
(instance i38 NamedIndividual)
(instance i20 NamedIndividual)
(instance i51 NamedIndividual)
(instance i33 NamedIndividual)
(instance i8 NamedIndividual)
(instance i23 NamedIndividual)
(instance i10 NamedIndividual)
(instance i46 NamedIndividual)
(instance i6 NamedIndividual)
(instance i53 NamedIndividual)
(instance i12 NamedIndividual)
(instance i19 NamedIndividual)
(instance i49 NamedIndividual)
(instance i22 NamedIndividual)
(instance i7 NamedIndividual)
(instance i17 NamedIndividual)
(instance i25 NamedIndividual)
(instance i43 NamedIndividual)
(instance i50 NamedIndividual)
(instance i48 NamedIndividual)
(instance i54 NamedIndividual)
(instance i14 NamedIndividual)
(instance i29 NamedIndividual)
(instance i44 NamedIndividual)
(instance i37 NamedIndividual)
(instance i26 NamedIndividual)
(instance i16 NamedIndividual)
(instance i27 NamedIndividual)
(instance i31 NamedIndividual)
(instance i11 NamedIndividual)
(instance i28 NamedIndividual)
(instance i39 NamedIndividual)
(instance i24 NamedIndividual)
(instance i47 NamedIndividual)
(instance i3 NamedIndividual)
(instance i5 NamedIndividual)
(instance i21 NamedIndividual)
(instance i13 NamedIndividual)
(instance i9 NamedIndividual)
(instance i34 NamedIndividual)
(instance i36 NamedIndividual)
(instance i1 NamedIndividual)
(instance i32 NamedIndividual)
(instance i42 NamedIndividual)
(instance i55 NamedIndividual)
(instance i4 NamedIndividual)
(instance i15 NamedIndividual)
(instance i45 NamedIndividual)
(instance i40 NamedIndividual)
(instance i41 NamedIndividual)
(instance i52 NamedIndividual)
(instance i35 NamedIndividual)
(instance i18 NamedIndividual)
(instance i2 NamedIndividual)
(functional hasSex)
(functional hasFather)
(functional hasMother)
(symmetric isThirdCousinOf)
(symmetric isSecondCousinOf)
(symmetric isSiblingOf)
(symmetric isFirstCousinOf)
(symmetric hasRelation)
(transitive isSiblingOf)
(transitive hasAncestor)
(domain isAuntOf Woman)
(domain hasPartner Marriage)
(domain isGreatUncleOf Man)
(domain hasMother Person)
(domain hasMalePartner Marriage)
(domain hasFather Person)
(domain isBrotherOf Man)
(domain isSisterOf Woman)
(domain hasSex Person)
(domain hasGrandParent Person)
(domain isGreatAuntOf Woman)
(domain hasParent Person)
(domain hasFemalePartner Marriage)
(domain hasRelation Person)
(domain hasGreatGrandParent Person)
(domain isUncleOf Man)
(range hasWife Woman)
(range hasGreatGrandmother Woman)
(range hasParent Person)
(range isGreatUncleOf Person)
(range isAuntOf Person)
(range hasGrandfather Man)
(range hasMalePartner Man)
(range hasGrandmother Woman)
(range hasFather Man)
(range hasPartner Person)
(range hasGrandParent Person)
(range hasGreatGrandfather Man)
(range hasGreatGrandParent Person)
(range hasHusband Man)
(range isBrotherOf Person)
(range hasFemalePartner Woman)
(range isGreatAuntOf Person)
(range isSisterOf Person)
(range hasSex Sex)
(range hasRelation Person)
(range isUncleOf Person)
(range hasMother Woman)
(implies_r hasParent hasAncestor)
(implies_r hasSon hasChild)
(implies_r hasGreatGrandmother hasGreatGrandParent)
(implies_r isSisterOf isSiblingOf)
(implies_r hasAncestor hasRelation)
(implies_r hasWife hasSpouse)
(implies_r hasGrandParent hasAncestor)
(implies_r isSecondCousinOf isCousinOf)
(implies_r isFirstCousinOf isCousinOf)
(implies_r isSonOf isChildOf)
(implies_r hasMother hasParent)
(implies_r isDaughterOf isChildOf)
(implies_r hasGreatGrandParent hasAncestor)
(implies_r hasGrandfather hasGrandParent)
(implies_r isCousinOf isBloodrelationOf)
(implies_r hasDaughter hasChild)
(implies_r hasMalePartner hasPartner)
(implies_r hasGrandmother hasGrandParent)
(implies_r hasGreatGrandfather hasGreatGrandParent)
(implies_r isBloodrelationOf hasRelation)
(implies_r hasFemalePartner hasPartner)
(implies_r isBrotherOf isSiblingOf)
(implies_r isThirdCousinOf isCousinOf)
(implies_r isSiblingOf isBloodrelationOf)
(implies_r hasFather hasParent)
(implies_r hasHusband hasSpouse)
(equal_r hasParent isChildOf)
(equal_r hasSpouse (inv isSpouseOf))
(equal_r isHusbandOf (inv hasHusband))
(equal_r isAncestorOf (inv hasAncestor))
(equal_r hasUncle (inv isUncleOf))
(equal_r isChildOf (inv hasChild))
(equal_r isGrandmotherOf (inv hasGrandmother))
(equal_r isGreatGrandmotherOf (inv hasGreatGrandmother))
(equal_r hasParent (inv isParentOf))
(equal_r hasGreatUncle (inv isGreatUncleOf))
(equal_r hasMother (inv isMotherOf))
(equal_r hasMalePartner (inv isMalePartnerIn))
(equal_r hasFather (inv isFatherOf))
(equal_r isWifeOf (inv hasWife))
(equal_r isGrandfatherOf (inv hasGrandfather))
(equal_r isGreatGrandParentOf (inv hasGreatGrandParent))
(equal_r hasGreatAunt (inv isGreatAuntOf))
(equal_r isGreatGrandfatherOf (inv hasGreatGrandfather))
(equal_r isGrandParentOf (inv hasGrandParent))
(equal_r hasAunt (inv isAuntOf))
(equal_r hasFemalePartner (inv isFemalePartnerIn))
(equal_r isSonOf (inv hasSon))
(equal_r isDaughterOf (inv hasDaughter))
(equal_r hasPartner (inv isPartnerIn))
(implies_r (compose hasParent hasFather) hasGrandfather)
(implies_r (compose hasParent hasParent hasParent) hasGreatGrandParent)
(implies_r (compose hasParent hasGrandfather) hasGreatGrandfather)
(implies_r (compose hasParent hasMother) hasGrandmother)
(implies_r (compose hasGrandParent isSiblingOf isGrandParentOf) isSecondCousinOf)
(implies_r (compose isBrotherOf isParentOf) isUncleOf)
(implies_r (compose isFemalePartnerIn hasMalePartner) hasHusband)
(implies_r (compose hasGreatGrandParent isSiblingOf isGreatGrandParentOf) isThirdCousinOf)
(implies_r (compose isSisterOf isGrandParentOf) isGreatAuntOf)
(implies_r (compose hasParent hasParent) hasGrandParent)
(implies_r (compose hasParent hasGrandmother) hasGreatGrandmother)
(implies_r (compose hasParent isSiblingOf isParentOf) isFirstCousinOf)
(implies_r (compose isMalePartnerIn hasFemalePartner) hasWife)
(implies_r (compose isBrotherOf isGrandParentOf) isGreatUncleOf)
(implies_r (compose isSisterOf isParentOf) isAuntOf)
(implies_r (compose hasParent isParentOf) isSiblingOf)
(related i28 isFatherOf i31)
(related i52 hasMalePartner i28)
(related i31 isBrotherOf i33)
(related i49 hasMalePartner i17)
(related i18 isMotherOf i20)
(related i26 isFatherOf i28)
(related i17 isFatherOf i20)
(related i46 hasFemalePartner i4)
(related i45 hasMalePartner i15)
(related i50 hasFemalePartner i23)
(related i7 isSisterOf i6)
(related i8 isBrotherOf i6)
(related i23 isMotherOf i26)
(related i51 hasMalePartner i26)
(related i42 hasMalePartner i2)
(related i14 isMotherOf i16)
(related i48 hasFemalePartner i21)
(related i7 isSisterOf i8)
(related i2 isFatherOf i7)
(related i55 hasMalePartner i37)
(related i37 isFatherOf i39)
(related i54 hasFemalePartner i36)
(related i44 hasFemalePartner i10)
(related i48 hasMalePartner i20)
(related i34 isMotherOf i35)
(related i55 hasFemalePartner i38)
(related i3 isMotherOf i7)
(related i46 hasMalePartner i2)
(related i0 isFatherOf i2)
(related i1 isMotherOf i2)
(related i53 hasFemalePartner i34)
(related i17 isFatherOf i24)
(related i23 isSisterOf i24)
(related i35 isFatherOf i37)
(related i53 hasMalePartner i33)
(related i9 isMotherOf i10)
(related i27 isMotherOf i28)
(related i8 isFatherOf i10)
(related i41 hasFemalePartner i1)
(related i13 isFatherOf i14)
(related i9 isMotherOf i11)
(related i20 isFatherOf i22)
(related i8 isFatherOf i11)
(related i2 isFatherOf i17)
(related i28 isFatherOf i33)
(related i42 hasFemalePartner i3)
(related i33 isFatherOf i35)
(related i2 isFatherOf i8)
(related i11 isSisterOf i10)
(related i15 isFatherOf i16)
(related i8 isBrotherOf i7)
(related i3 isMotherOf i6)
(related i54 hasMalePartner i35)
(related i43 hasMalePartner i8)
(related i25 isFatherOf i26)
(related i4 isMotherOf i17)
(related i3 isMotherOf i8)
(related i47 hasMalePartner i17)
(related i44 hasMalePartner i13)
(related i51 hasFemalePartner i27)
(related i38 isMotherOf i39)
(related i47 hasFemalePartner i18)
(related i52 hasFemalePartner i30)
(related i17 isFatherOf i23)
(related i33 isBrotherOf i31)
(related i43 hasFemalePartner i9)
(related i30 isMotherOf i33)
(related i21 isMotherOf i22)
(related i45 hasFemalePartner i14)
(related i10 isSisterOf i11)
(related i2 isFatherOf i6)
(related i41 hasMalePartner i0)
(related i6 isBrotherOf i7)
(related i49 hasFemalePartner i19)
(related i6 isBrotherOf i8)
(related i36 isMotherOf i37)
(related i19 isMotherOf i24)
(related i24 isSisterOf i23)
(related i30 isMotherOf i31)
(related i10 isMotherOf i14)
(related i19 isMotherOf i23)
(related i50 hasMalePartner i25)
